package diff

import (
	"strings"
	"testing"
)

func TestProcess(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		maxLen  int
		check   func(t *testing.T, result string)
	}{
		{
			name:   "empty diff returns empty",
			input:  "",
			maxLen: 20000,
			check: func(t *testing.T, result string) {
				if result != "" {
					t.Errorf("expected empty, got %q", result)
				}
			},
		},
		{
			name: "clean diff under budget is unchanged",
			input: "diff --git a/main.go b/main.go\n" +
				"--- a/main.go\n" +
				"+++ b/main.go\n" +
				"@@ -1,3 +1,3 @@\n" +
				"-old line\n" +
				"+new line\n",
			maxLen: 20000,
			check: func(t *testing.T, result string) {
				if !strings.Contains(result, "new line") {
					t.Error("expected original content preserved")
				}
			},
		},
		{
			name: "lock file replaced with placeholder",
			input: "diff --git a/go.sum b/go.sum\n" +
				"--- a/go.sum\n" +
				"+++ b/go.sum\n" +
				"@@ -1,100 +1,101 @@\n" +
				"+some hash line\n",
			maxLen: 20000,
			check: func(t *testing.T, result string) {
				if !strings.Contains(result, "[lock file: go.sum changed]") {
					t.Errorf("expected lock file placeholder, got %q", result)
				}
				if strings.Contains(result, "some hash line") {
					t.Error("lock file content should be filtered out")
				}
			},
		},
		{
			name: "package-lock.json filtered",
			input: "diff --git a/package-lock.json b/package-lock.json\n" +
				"+lots of json\n",
			maxLen: 20000,
			check: func(t *testing.T, result string) {
				if !strings.Contains(result, "[lock file: package-lock.json changed]") {
					t.Errorf("expected lock file placeholder, got %q", result)
				}
			},
		},
		{
			name: "generated code by filename replaced with placeholder",
			input: "diff --git a/api.pb.go b/api.pb.go\n" +
				"--- a/api.pb.go\n" +
				"+++ b/api.pb.go\n" +
				"+generated stuff\n",
			maxLen: 20000,
			check: func(t *testing.T, result string) {
				if !strings.Contains(result, "[generated file: api.pb.go changed]") {
					t.Errorf("expected generated file placeholder, got %q", result)
				}
			},
		},
		{
			name: "generated code by content marker",
			input: "diff --git a/foo.go b/foo.go\n" +
				"--- a/foo.go\n" +
				"+++ b/foo.go\n" +
				"@@ -1,3 +1,3 @@\n" +
				" // Code generated by stringer; DO NOT EDIT.\n" +
				"+var x = 1\n",
			maxLen: 20000,
			check: func(t *testing.T, result string) {
				if !strings.Contains(result, "[generated file: foo.go changed]") {
					t.Errorf("expected generated file placeholder, got %q", result)
				}
			},
		},
		{
			name: "binary file replaced with placeholder",
			input: "diff --git a/logo.png b/logo.png\n" +
				"Binary files /dev/null and b/logo.png differ\n",
			maxLen: 20000,
			check: func(t *testing.T, result string) {
				if !strings.Contains(result, "[binary file: logo.png changed]") {
					t.Errorf("expected binary file placeholder, got %q", result)
				}
			},
		},
		{
			name: "vendor file replaced with placeholder",
			input: "diff --git a/vendor/lib/foo.go b/vendor/lib/foo.go\n" +
				"+package lib\n",
			maxLen: 20000,
			check: func(t *testing.T, result string) {
				if !strings.Contains(result, "[vendor file: foo.go changed]") {
					t.Errorf("expected vendor placeholder, got %q", result)
				}
			},
		},
		{
			name: "large diff truncates lower-tier files first",
			input: makeDiff("main.go", 100) + "\n" +
				makeDiff("README.md", 500),
			maxLen: 300,
			check: func(t *testing.T, result string) {
				// Source file (tier 1) should be preserved or truncated last.
				// Doc file (tier 4) should be truncated or replaced first.
				if !strings.Contains(result, "main.go") {
					t.Error("expected main.go to be referenced")
				}
				if strings.Contains(result, "README.md line ") {
					t.Error("expected README.md content to be truncated")
				}
			},
		},
		{
			name: "very large single file gets truncated",
			input: makeDiff("big.go", 2000),
			maxLen: 200,
			check: func(t *testing.T, result string) {
				if len(result) > 250 { // some slack for truncation marker
					t.Errorf("expected result under budget, got len %d", len(result))
				}
				if !strings.Contains(result, "truncated") && !strings.Contains(result, "omitted") {
					t.Error("expected truncation marker")
				}
			},
		},
		{
			name: "tier priority order under budget constraint",
			input: makeDiff("cmd/main.go", 200) + "\n" +
				makeDiff(".github/workflows/ci.yml", 200) + "\n" +
				makeDiff("handler_test.go", 200) + "\n" +
				makeDiff("README.md", 200) + "\n" +
				makeDiff(".prettierrc", 200),
			maxLen: 600,
			check: func(t *testing.T, result string) {
				// Tier 5 (.prettierrc) and tier 4 (README.md) should be
				// truncated/replaced before tier 1 (main.go).
				hasSource := strings.Contains(result, "cmd/main.go line ")
				hasPrettier := strings.Contains(result, ".prettierrc line ")
				if !hasSource && hasPrettier {
					t.Error("source code should be preserved over style config")
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := Process(tt.input, tt.maxLen)
			tt.check(t, result)
		})
	}
}

func TestClassifyTier(t *testing.T) {
	tests := []struct {
		path string
		want int
	}{
		{"main.go", tierSource},
		{"internal/foo/bar.go", tierSource},
		{"app.ts", tierSource},
		{"index.jsx", tierSource},
		{"lib.rs", tierSource},
		{"Dockerfile", tierConfig},
		{"docker-compose.yml", tierConfig},
		{".github/workflows/ci.yml", tierConfig},
		{"go.mod", tierConfig},
		{"package.json", tierConfig},
		{"foo_test.go", tierTest},
		{"app.test.ts", tierTest},
		{"handler.spec.js", tierTest},
		{"tests/integration.py", tierTest},
		{"test/helper.go", tierTest},
		{"README.md", tierDocs},
		{"docs/guide.rst", tierDocs},
		{".eslintrc.json", tierStyle},
		{".prettierrc", tierStyle},
		{".editorconfig", tierStyle},
		{".gitignore", tierStyle},
	}

	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			got := classifyTier(tt.path)
			if got != tt.want {
				t.Errorf("classifyTier(%q) = %d, want %d", tt.path, got, tt.want)
			}
		})
	}
}

// makeDiff creates a fake diff section for a file with approximately n
// characters of hunk content.
func makeDiff(path string, n int) string {
	header := "diff --git a/" + path + " b/" + path + "\n" +
		"--- a/" + path + "\n" +
		"+++ b/" + path + "\n" +
		"@@ -1,5 +1,5 @@\n"
	var b strings.Builder
	b.WriteString(header)
	for b.Len() < n {
		b.WriteString("+" + path + " line content padding\n")
	}
	return b.String()
}
